# Generated by Django 4.1.5 on 2023-01-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_videoproxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='acrive',
            field=models.BooleanField(default=False),
        ),
    ]
