# Generated by Django 4.1.5 on 2023-01-06 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_video_acrive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='acrive',
            new_name='active',
        ),
    ]
