# Generated by Django 4.1.5 on 2023-01-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_alter_video_options_video_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='puplish_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
